services:
  discordbot:
    container_name: discordbot
    image: regunakyle/my-discord-bot:latest
    environment:
      DISCORD_TOKEN: <Your token here>
      # Used by old style prefix commands; this bot only has the <PREFIX>sync prefix command
      PREFIX: ">>"
      # Maximum file upload size (in MiB), used by command like /pixiv
      MAX_FILE_SIZE: 10
      # Lavalink parameters, used by the Music module
      # The Music module will be disabled if LAVALINK_URL is empty
      LAVALINK_URL: http://lavalink:2333
      LAVALINK_PASSWORD: youshallnotpass
      # AI related parameters
      # The AI module will be disabled if OPENAI_API_KEY or OPENAI_MODEL_NAME is empty
      # You can use a random string for OPENAI_API_KEY if you are using an custom OpenAI-compatible API server
      OPENAI_API_KEY:
      OPENAI_MODEL_NAME: gpt-3.5-turbo
      # If OPENAI_BASE_URL is empty, use OpenAI API endpoint instead
      OPENAI_BASE_URL: http://localhost:5000/v1
    volumes:
      - dbot-vol:/app/volume
    depends_on:
      lavalink:
        condition: service_started
    restart: unless-stopped

  lavalink:
    container_name: lavalink
    image: ghcr.io/lavalink-devs/lavalink:latest
    environment:
      SERVER_PORT: 2333
      LAVALINK_SERVER_PASSWORD: youshallnotpass
      LAVALINK_SERVER_SOURCES_YOUTUBE: "false"
      # See https://github.com/lavalink-devs/youtube-source for the latest version of the plugin
      LAVALINK_PLUGINS_0_DEPENDENCY: dev.lavalink.youtube:youtube-plugin:1.13.2
      PLUGINS_YOUTUBE_ENABLED: "true"
      PLUGINS_YOUTUBE_CLIENTS_0: MUSIC
      PLUGINS_YOUTUBE_CLIENTS_1: WEB
      PLUGINS_YOUTUBE_CLIENTS_2: MWEB
      PLUGINS_YOUTUBE_CLIENTS_3: WEBEMBEDDED
      PLUGINS_YOUTUBE_CLIENTS_4: ANDROID_MUSIC
      PLUGINS_YOUTUBE_CLIENTS_5: ANDROID_VR
      PLUGINS_YOUTUBE_CLIENTS_6: TV
      PLUGINS_YOUTUBE_CLIENTS_7: TVHTML5EMBEDDED
      # See https://github.com/lavalink-devs/youtube-source?tab=readme-ov-file#using-oauth-tokens for more info
      PLUGINS_YOUTUBE_OAUTH_ENABLED: "true"
      PLUGINS_YOUTUBE_OAUTH_REFRESHTOKEN: <Use your own oauth token here>
    restart: unless-stopped

volumes:
  dbot-vol:
    name: discord-bot-vol

networks:
  default:
    name: discord-bot-network
