services:
  discordbot:
    container_name: discordbot
    image: regunakyle/my-discord-bot:latest
    environment:
      DISCORD_TOKEN: <YOUR_TOKEN_HERE>
      # Used by old style prefix commands; this bot only has the <PREFIX>sync prefix command
      PREFIX: ">>"
      # Maximum file upload size, used by command like /pixiv
      MAX_FILE_SIZE: 25
      # Lavalink parameters, used by the Music module
      LAVALINK_IP: lavalink
      LAVALINK_PORT: 2333
      LAVALINK_PASSWORD: youshallnotpass
    volumes:
      - dbot-vol:/app/volume
    restart: unless-stopped

  lavalink:
    container_name: lavalink
    # Using fix-yt-400 until Lavalink fix the 400 issue
    # https://github.com/lavalink-devs/lavaplayer/issues/69
    image: ghcr.io/lavalink-devs/lavalink:fix-yt-400
    environment:
      server.port: 2333
      lavalink.server.password: youshallnotpass
    ports:
      - 2333:2333
    restart: unless-stopped

volumes:
  dbot-vol:
    name: discord-bot-vol

networks:
  default:
    name: discord-bot-network
