version: "3.9"
services:
  discordbot:
    container_name: discordbot
    image: regunakyle/discordbot
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN} # Your discord token here
      PYTHONUNBUFFERED: 1
    volumes:
      - dbot-vol:/app/volume
    restart: unless-stopped
volumes:
  dbot-vol:
    name: dbot-vol
