[tool.poetry]
name = "my-discord-bot"
version = "3.1.1"
description = "Discord Bot by Reguna"
authors = ["Reguna <60984878+regunakyle@users.noreply.github.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
gallery-dl = "^1"
python-dotenv = "^1"
"discord.py" = { extras = ["voice"], version = "^2" }
wavelink = "^3"
sqlalchemy = { extras = ["asyncio"], version = "^2" }
aiosqlite = "^0"
aiohttp = "^3"
openai = "^1"
pygit2 = "^1"

[tool.poetry.group.dev.dependencies]
ipykernel = "*"
ruff = "*"

[tool.pyright]
reportCallInDefaultInitializer = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
