[tool.poetry]
name = "discordbot"
version = "2.0.0"
description = "Discord Bot by Reguna"
authors = ["Reguna <60984878+regunakyle@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.11"
feedparser = "^6"
gallery-dl = "^1"
python-dotenv = "^1"
"discord.py" = { extras = ["voice"], version = "^2" }
wavelink = "^1"
sqlalchemy = { extras = ["asyncio"], version = "^2" }
aiosqlite = "^0"
aiohttp = "^3"

[tool.poetry.dev-dependencies]
ipykernel = "*"
black = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
