[tool.poetry]
name = "my-discord-bot"
version = "2.3.1"
description = "Discord Bot by Reguna"
authors = ["Reguna <60984878+regunakyle@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.11"
feedparser = "^6"
gallery-dl = "^1"
python-dotenv = "^1"
"discord.py" = { extras = ["voice"], version = "^2" }
wavelink = "^2"
sqlalchemy = { extras = ["asyncio"], version = "^2" }
aiosqlite = "^0"
aiohttp = "^3"

[tool.poetry.group.dev.dependencies]
mypy = "*"
ipykernel = "*"
black = "*"
dpytest = "*"
pytest = "*"

[tool.mypy]
strict = true
warn_return_any = false

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
