"""Add subscription

Revision ID: 6a50145180fd
Revises: 93832be8c5ae
Create Date: 2026-06-11 01:41:08.971231

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6a50145180fd"
down_revision: Union[str, None] = "93832be8c5ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription",
        sa.Column(
            "id",
            sa.Integer(),
            sa.Identity(always=True, start=1, increment=1),
            nullable=False,
        ),
        sa.Column("guild_id", sa.Integer(), nullable=False),
        sa.Column(
            "youtube_channel_name",
            sa.Unicode(length=100).with_variant(sa.TEXT, "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "youtube_channel_id",
            sa.String(length=50).with_variant(sa.TEXT(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "youtube_upload_playlist",
            sa.String(length=50).with_variant(sa.TEXT(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "announcement_target",
            sa.String(length=50).with_variant(sa.TEXT(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "last_checked_at",
            sa.DateTime().with_variant(sa.TEXT(), "sqlite"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guild.id"],
            name=op.f("fk_subscription_guild_id_guild"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription")),
        sa.UniqueConstraint(
            "youtube_channel_id", name=op.f("uq_subscription_youtube_channel_id")
        ),
        sqlite_strict=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subscription")
    # ### end Alembic commands ###
