"""Refactor translation

Revision ID: 83974dbb16bb
Revises: 913bd89d08a9
Create Date: 2026-06-28 18:25:09.057256

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "83974dbb16bb"
down_revision: Union[str, None] = "913bd89d08a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("translation", "chinese_channel_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "translation", sa.Column("chinese_channel_id", sa.INTEGER(), nullable=False)
    )
    # ### end Alembic commands ###
