"""Add translation

Revision ID: 913bd89d08a9
Revises: 6a50145180fd
Create Date: 2026-06-23 01:06:18.834286

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "913bd89d08a9"
down_revision: Union[str, None] = "6a50145180fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "translation",
        sa.Column(
            "id",
            sa.Integer(),
            sa.Identity(always=True, start=1, increment=1),
            nullable=False,
        ),
        sa.Column("guild_id", sa.Integer(), nullable=False),
        sa.Column(
            "trigger_emote",
            sa.Unicode(length=50).with_variant(sa.TEXT(), "sqlite"),
            nullable=False,
        ),
        sa.Column("chinese_channel_id", sa.Integer(), nullable=False),
        sa.Column("english_channel_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guild.id"],
            name=op.f("fk_translation_guild_id_guild"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_translation")),
        sa.UniqueConstraint("guild_id", name=op.f("uq_translation_guild_id")),
        sqlite_strict=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("translation")
    # ### end Alembic commands ###
