"""Add subscription

Revision ID: fec7b1c16b86
Revises: 4086cccce064
Create Date: 2025-10-21 01:55:05.679872

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fec7b1c16b86"
down_revision: Union[str, None] = "4086cccce064"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription",
        sa.Column(
            "id",
            sa.Integer(),
            sa.Identity(always=True, start=1, increment=1),
            nullable=False,
        ),
        sa.Column("guild_id", sa.Integer(), nullable=False),
        sa.Column("youtube_channel_name", sa.Unicode(length=50), nullable=False),
        sa.Column("youtube_channel_id", sa.Integer(), nullable=False),
        sa.Column("youtube_upload_playlist", sa.String(length=50), nullable=False),
        sa.Column("announcement_target", sa.String(length=50), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription")),
        sa.UniqueConstraint(
            "youtube_channel_id", name=op.f("uq_subscription_youtube_channel_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subscription")
    # ### end Alembic commands ###
