"""Shared constants for the bot."""

# Translation cog
ACK_EMOJI = "✅"
TRANSLATION_HEADER_PREFIX = "[TRANSLATION] "
TRANSLATION_HEADER_TEMPLATE = "[TRANSLATION] {0} | <#{1}> | {2}"

# Streaming
DISCORD_MAX_MESSAGE_LENGTH = 2000
STREAM_EDIT_INTERVAL = 1.0
