name: Build Docker image and push to Dockerhub

on:
  push:
    branches:
      - main
      - dev

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set variables
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "DOCKER_TAG_NAME=latest" >> $GITHUB_ENV
            echo "APP_VERSION=$(yq -oy '.project.version' pyproject.toml)" >> $GITHUB_ENV
          else
            echo "DOCKER_TAG_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
            echo "APP_VERSION=dev-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          fi
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ github.repository }}:${{ env.DOCKER_TAG_NAME }}
          # https://github.com/docker/build-push-action/issues/557
          build-args: |
            APP_VERSION=${{ env.APP_VERSION }}
      - name: Push README to Dockerhub
        uses: peter-evans/dockerhub-description@v3
        if: github.ref_name == 'main'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          short-description: ${{ github.event.repository.description }}
          enable-url-completion: true
